DELETE http://localhost:3001/api/blogs/603cdc6c2dd9795fe12c3f8d
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hcmlzIiwiaWQiOiI2MDNjY2Y1ZmU4NTdjMDU0NTM1OWMwOWUiLCJpYXQiOjE2MTQ2MTc4NDV9.13O4dyHi7aD86CoRqZf_KcKrhzkdpY6vlKIqEttdR88
